export enum ExitCode {
  SUCCESS = 0,
  ALREADY_RECEIVED = 1,
  NEED_SMS_AUTH = 2,
  CANNOT_SOLVE_PUZZLE = 3,
  OPERATION_TIMEOUT_EXCEEDED = 4,
  NEED_EMAIL_AUTH = 5,
  LOGIN_DENIED = 6,
  TOO_MUCH_TRY = 69,
  INVALID_OPTIONS = 77,
  WRONG_PASSWORD = 87,
  UNKNOWN_ERROR = 88
}
